//! The MT19937 Mersenne Twister, seeded exactly as NumPy's legacy `RandomState`.
//!
//! `RandomState(int_seed)` uses Knuth's `init_genrand` seeding for a scalar seed
//! in `[0, 2³²)`, and `init_by_array` for an array seed. Both are reproduced
//! here bit-for-bit (verified against `np.random.RandomState(...).random_raw`).

const N: usize = 624;
const M: usize = 397;
const MATRIX_A: u32 = 0x9908_b0df;
const UPPER_MASK: u32 = 0x8000_0000;
const LOWER_MASK: u32 = 0x7fff_ffff;

/// The Mersenne Twister state plus its read position.
#[derive(Clone)]
pub struct Mt19937 {
    /// The 624-word state vector.
    key: [u32; N],
    /// Read cursor into `key`; `pos >= N` means the block is exhausted and must
    /// be regenerated by [`Mt19937::twist`] before the next output.
    pos: usize,
}

impl Mt19937 {
    /// Seed from a scalar, matching `mt19937_seed` / Knuth `init_genrand`.
    ///
    /// Fills the state with the recurrence
    /// `key[i] = 1812433253 * (key[i-1] ^ (key[i-1] >> 30)) + i`.
    ///
    /// # Arguments
    /// * `seed` — the initial 32-bit state word `key[0]`.
    ///
    /// # Returns
    /// A generator positioned past the state block (`pos = N`), so the first
    /// output triggers a twist.
    pub fn new_seed(seed: u32) -> Self {
        let mut key = [0u32; N];
        key[0] = seed;
        for i in 1..N {
            key[i] = 1812433253u32
                .wrapping_mul(key[i - 1] ^ (key[i - 1] >> 30))
                .wrapping_add(i as u32);
        }
        Mt19937 { key, pos: N }
    }

    /// Seed from an array, matching `mt19937_init_by_array`.
    ///
    /// Seeds `key` from the fixed constant `19650218`, then folds in the seed
    /// words over two mixing passes before forcing `key[0] = 0x80000000`.
    ///
    /// # Arguments
    /// * `init_key` — the seed words; must be non-empty.
    ///
    /// # Returns
    /// A generator positioned past the state block (`pos = N`).
    ///
    /// # Panics
    /// Panics if `init_key` is empty.
    pub fn new_by_array(init_key: &[u32]) -> Self {
        assert!(!init_key.is_empty(), "array seed must be non-empty");
        let mut key = Self::new_seed(19650218).key;
        let mut i = 1usize;
        let mut j = 0usize;
        let mut k = N.max(init_key.len());
        while k > 0 {
            key[i] = (key[i] ^ (key[i - 1] ^ (key[i - 1] >> 30)).wrapping_mul(1664525))
                .wrapping_add(init_key[j])
                .wrapping_add(j as u32);
            i += 1;
            j += 1;
            if i >= N {
                key[0] = key[N - 1];
                i = 1;
            }
            if j >= init_key.len() {
                j = 0;
            }
            k -= 1;
        }
        k = N - 1;
        while k > 0 {
            key[i] = (key[i] ^ (key[i - 1] ^ (key[i - 1] >> 30)).wrapping_mul(1566083941))
                .wrapping_sub(i as u32);
            i += 1;
            if i >= N {
                key[0] = key[N - 1];
                i = 1;
            }
            k -= 1;
        }
        key[0] = 0x8000_0000;
        Mt19937 { key, pos: N }
    }

    /// Regenerate the 624-word state block (the "twist").
    ///
    /// Applies the MT19937 recurrence in place over all `N` words using the
    /// upper/lower bit masks and the `MATRIX_A` twist constant, then resets the
    /// read position to `0`.
    fn twist(&mut self) {
        let mt = &mut self.key;
        for i in 0..N {
            let y = (mt[i] & UPPER_MASK) | (mt[(i + 1) % N] & LOWER_MASK);
            let mag = if y & 1 == 1 { MATRIX_A } else { 0 };
            mt[i] = mt[(i + M) % N] ^ (y >> 1) ^ mag;
        }
        self.pos = 0;
    }

    /// Next tempered 32-bit output.
    ///
    /// Twists the state block first if it is exhausted, then applies MT19937's
    /// four-step tempering to the current word.
    ///
    /// # Returns
    /// The next 32-bit value in the stream.
    pub fn next_u32(&mut self) -> u32 {
        if self.pos >= N {
            self.twist();
        }
        let mut y = self.key[self.pos];
        self.pos += 1;
        y ^= y >> 11;
        y ^= (y << 7) & 0x9d2c_5680;
        y ^= (y << 15) & 0xefc6_0000;
        y ^= y >> 18;
        y
    }

    /// Next 64-bit output: high word drawn first, matching `mt19937_next64`.
    ///
    /// Draws two 32-bit words and packs them as `(hi << 32) | lo`.
    ///
    /// # Returns
    /// The next 64-bit value in the stream.
    pub fn next_u64(&mut self) -> u64 {
        let hi = self.next_u32() as u64;
        let lo = self.next_u32() as u64;
        (hi << 32) | lo
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rng::golden;

    fn first8(mut mt: Mt19937) -> [u32; 8] {
        let mut out = [0u32; 8];
        for o in out.iter_mut() {
            *o = mt.next_u32();
        }
        out
    }

    #[test]
    fn raw_stream_matches_numpy() {
        assert_eq!(first8(Mt19937::new_seed(0)), golden::RAW_SEED_0);
        assert_eq!(first8(Mt19937::new_seed(1)), golden::RAW_SEED_1);
        assert_eq!(first8(Mt19937::new_seed(42)), golden::RAW_SEED_42);
        assert_eq!(first8(Mt19937::new_seed(12345)), golden::RAW_SEED_12345);
    }

    #[test]
    fn twist_boundary_matches_numpy() {
        // Cross the 624-word regeneration boundary, then check words 624..632.
        let mut mt = Mt19937::new_seed(42);
        for _ in 0..624 {
            mt.next_u32();
        }
        let mut after = [0u32; 8];
        for a in after.iter_mut() {
            *a = mt.next_u32();
        }
        assert_eq!(after, golden::RAW_SEED_42_AFTER_624);
    }
}
