#!/usr/bin/env python3
"""Generate NumPy `RandomState` golden values for the Rust RNG tests.

    python tools/gen_rng_golden.py [output_path]

The Rust `rng` module must reproduce every value here exactly.
"""
import sys
import numpy as np


def fr(x):
    """Shortest round-tripping decimal for an f64."""
    return repr(float(x))


def arr_u32(name, vals):
    body = ", ".join(str(int(v)) for v in vals)
    return f"pub const {name}: [u32; {len(vals)}] = [{body}];\n"


def arr_i64(name, vals):
    body = ", ".join(str(int(v)) for v in vals)
    return f"pub const {name}: [i64; {len(vals)}] = [{body}];\n"


def arr_f64(name, vals):
    body = ", ".join(fr(v) for v in vals)
    return f"pub const {name}: [f64; {len(vals)}] = [{body}];\n"


def scalar_f64(name, v):
    return f"pub const {name}: f64 = {fr(v)};\n"


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "src/rng/golden.rs"
    parts = [
        "//! AUTO-GENERATED by tools/gen_rng_golden.py — DO NOT EDIT BY HAND.\n",
        "//!\n",
        "//! Bit-exact golden values captured from NumPy's legacy `RandomState`.\n",
        "#![allow(clippy::all)]\n",
        "#![allow(dead_code)]\n\n",
    ]

    # --- raw uint32 stream (seeding + tempering) ---
    for seed in [0, 1, 42, 12345]:
        rs = np.random.RandomState(seed)
        raw = rs._bit_generator.random_raw(8)
        parts.append(arr_u32(f"RAW_SEED_{seed}", raw))
    # raw stream across the 624-word regeneration boundary (the "twist")
    rs = np.random.RandomState(42)
    raw632 = rs._bit_generator.random_raw(632)
    parts.append(arr_u32("RAW_SEED_42_AFTER_624", raw632[624:632]))
    parts.append("\n")

    # --- random_sample (53-bit doubles) ---
    parts.append(arr_f64("SAMPLE_SEED_42", np.random.RandomState(42).random_sample(10)))
    s = np.random.RandomState(42).random_sample(1001)
    parts.append(scalar_f64("SAMPLE_SEED_42_AT_1000", s[1000]))
    parts.append("\n")

    # --- randint (default int64 dtype) ---
    parts.append(arr_i64("RANDINT_M20_20_S42", np.random.RandomState(42).randint(-20, 20, 12)))
    parts.append(arr_i64("RANDINT_0_3_S0", np.random.RandomState(0).randint(0, 3, 16)))
    parts.append(arr_i64("RANDINT_0_256_S42", np.random.RandomState(42).randint(0, 256, 12)))
    parts.append(arr_i64("RANDINT_0_2P40_S42", np.random.RandomState(42).randint(0, 2 ** 40, 5)))
    parts.append("\n")

    # --- continuous distributions (transcendental; tested with tolerance) ---
    parts.append(arr_f64("NORMAL_S42", np.random.RandomState(42).standard_normal(10)))
    parts.append(arr_f64("EXPONENTIAL_S7", np.random.RandomState(7).standard_exponential(8)))
    parts.append(arr_f64("GAMMA_SHAPE2P5_S3", np.random.RandomState(3).standard_gamma(2.5, 8)))
    parts.append(arr_f64("GAMMA_SHAPE0P4_S3", np.random.RandomState(3).standard_gamma(0.4, 8)))
    parts.append(arr_f64("GAMMA_3_SCALE2_S9", np.random.RandomState(9).gamma(3.0, 2.0, 6)))
    parts.append(arr_f64("DIRICHLET_2341_S5", np.random.RandomState(5).dirichlet([2.0, 3.0, 4.0, 1.0])))
    parts.append(arr_f64("DIRICHLET_THIRD_S11", np.random.RandomState(11).dirichlet([1 / 3, 1 / 3, 1 / 3])))
    # multivariate_normal draws exactly n standard_normal; check stream alignment
    # by capturing the next standard_normal after a 2-D draw.
    rng = np.random.RandomState(42)
    rng.multivariate_normal([1.0, 2.0], [[2.0, 0.5], [0.5, 1.0]])
    parts.append(scalar_f64("NORMAL_AFTER_MVN2_S42", rng.standard_normal()))
    parts.append("\n")

    # --- discrete distributions (integer results; tested exactly) ---
    parts.append(arr_i64("POISSON_3_S1", np.random.RandomState(1).poisson(3.0, 15)))
    parts.append(arr_i64("POISSON_15_S2", np.random.RandomState(2).poisson(15.0, 15)))
    parts.append(arr_i64("MULTINOMIAL_10_S3", np.random.RandomState(3).multinomial(10, [0.2, 0.3, 0.5])))
    parts.append(arr_i64("MULTINOMIAL_1_S8", np.random.RandomState(8).multinomial(1, [0.1, 0.6, 0.3])))
    parts.append(arr_i64("MULTINOMIAL_20_S9", np.random.RandomState(9).multinomial(20, [0.1, 0.2, 0.3, 0.4])))
    parts.append(arr_i64("CHOICE_3_S6", np.random.RandomState(6).choice(3, size=12, p=[0.2, 0.5, 0.3])))
    parts.append("\n")

    with open(out_path, "w") as f:
        f.writelines(parts)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
